### ISSUE TITLE
Doc HTML trimmed

### ISSUE THREAD

**Issue by simoneb** [paulbatum/WebSocket-Samples#1]
Hi Paul, this is mainly an issue with github but I reported it to them as the web view of docs with mixed line endings seems to be messed up and they didn't seem to care much. If you look at [this page](https://github.com/paulbatum/WebSocket-Samples/blob/gh-pages/docs/aspnetwebsocketecho/echohandler.ashx.html) you can see that the html is trimmed and missing a good bottom part.

**Comment by paulbatum** [comment]
I see the HTML is trimmed, but there is a hosted version here that should be much nicer to read:
http://paulbatum.github.com/WebSocket-Samples/AspNetWebSocketEcho/
